{
 "title": "Linux",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "prometheus", "query": "prometheus" },
   {
    "name": "monitor",
    "label": "Monitor",
    "query": {
     "query": "label_values(node_uname_info{sysname=\"Linux\"},monitor)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", monitor=\"$monitor\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "Sys Load",
   "type": "gauge",
   "description": "System load  over all CPU cores together",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(node_load1{monitor=\"$monitor\"}) * 100 / count(count(node_cpu_seconds_total{monitor=\"$monitor\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{monitor=\"$monitor\"} / node_memory_MemTotal_bytes{monitor=\"$monitor\"})) * 100"
    }
   ]
  },
  {
   "title": "Storage Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{monitor=\"$monitor\",mountpoint=\"/\"} * 100) / node_filesystem_size_bytes{monitor=\"$monitor\",mountpoint=\"/\"})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - node_boot_time_seconds{monitor=\"$monitor\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{monitor=\"$monitor\",mode=\"system\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{monitor=\"$monitor\"}) by (cpu)))",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{monitor=\"$monitor\",mode=\"user\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{monitor=\"$monitor\"}) by (cpu)))",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{monitor=\"$monitor\",mode=\"iowait\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{monitor=\"$monitor\"}) by (cpu)))",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{monitor=\"$monitor\",mode=~\".*irq\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{monitor=\"$monitor\"}) by (cpu)))",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{monitor=\"$monitor\",mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq'}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{monitor=\"$monitor\"}) by (cpu)))",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{monitor=\"$monitor\",mode=\"idle\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{monitor=\"$monitor\"}) by (cpu)))",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{monitor=\"$monitor\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{monitor=\"$monitor\"} - node_memory_MemFree_bytes{monitor=\"$monitor\"} - (node_memory_Cached_bytes{monitor=\"$monitor\"} + node_memory_Buffers_bytes{monitor=\"$monitor\"} + node_memory_SReclaimable_bytes{monitor=\"$monitor\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{monitor=\"$monitor\"} + node_memory_Buffers_bytes{monitor=\"$monitor\"} + node_memory_SReclaimable_bytes{monitor=\"$monitor\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{monitor=\"$monitor\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{monitor=\"$monitor\"} - node_memory_SwapFree_bytes{monitor=\"$monitor\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{monitor=\"$monitor\",device=~\"(en|eth).*\"}[$__rate_interval])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{monitor=\"$monitor\",device=~\"(en|eth).*\"}[$__rate_interval])*8",
     "legendFormat": "trans {{device}} "
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{monitor=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "reads"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{monitor=\"$monitor\"}[$__rate_interval])) * -1",
     "legendFormat": "writes"
    }
   ]
  },
  { "title": "Hardware Monitor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Temperature Sensors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "(node_hwmon_temp_celsius{monitor=\"$monitor\"} > 0) * on(chip) group_left(chip_name) node_hwmon_chip_names{monitor=\"$monitor\"}",
     "legendFormat": "{{ chip_name }} {{ sensor }}"
    }
   ]
  },
  {
   "title": "SSD Disk Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg(smartctl_device_temperature{monitor=\"$monitor\"} * on(monitor,device) group_left(interface,serial_number,model_name) smartctl_device) by (monitor,device,model_name) unless on(monitor,device) (smartctl_device_attribute{attribute_name=\"Start_Stop_Count\", attribute_value_type=\"raw\"} > 0)",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Fan Speeds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "node_hwmon_fan_rpm{monitor=\"$monitor\"} > 0",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "HDD Disk Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg(smartctl_device_temperature{monitor=\"$monitor\"} * on(monitor, device) group_left(interface,serial_number,model_name) smartctl_device) by (monitor,device,model_name) and on(monitor, device) (smartctl_device_attribute{attribute_name=\"Start_Stop_Count\", attribute_value_type=\"raw\"} > 0)",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}