{
 "title": "Processes",
 "tags": [ "system" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "prometheus", "query": "prometheus" },
   {
    "name": "monitor",
    "label": "Monitor",
    "query": {
     "query": "label_values(node_uname_info,monitor)"
    }
   },
   {
    "name": "processes",
    "label": "Process",
    "query": {
     "query": "label_values(namedprocess_namegroup_cpu_seconds_total{monitor=\"$monitor\"},groupname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(namedprocess_namegroup_cpu_seconds_total{monitor=\"$monitor\", groupname=~\"$processes\"}[$__interval])) by (groupname)",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Num Processes",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "namedprocess_namegroup_num_procs{monitor=\"$monitor\", groupname=~\"$processes\"} > 0",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Disk Read Bytes",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_read_bytes_total{monitor=\"$monitor\", groupname=~\"$processes\"}[$__interval]) > 0",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Disk Write Bytes",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_write_bytes_total{monitor=\"$monitor\", groupname=~\"$processes\"}[$__interval]) > 0",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Resident Memory",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "namedprocess_namegroup_memory_bytes{monitor=\"$monitor\", groupname=~\"$processes\", memtype=\"resident\"} > 0",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Virtual Memory",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "namedprocess_namegroup_memory_bytes{monitor=\"$monitor\", groupname=~\"$processes\", memtype=\"virtual\"} > 0",
     "legendFormat": "{{groupname}}"
    }
   ]
  }
 ]
}